### PR TITLE
Fix product image plugin - magento changed the visibility of getFilte…

### PR DESCRIPTION
**Pull request by delyriand**
…rArray method

### CODE REVIEW

**Comment by rbayet** [comment]
Hello @delyriand,

Our CI ensures compatibility of the 2.6.x branch with both 2.2.5 and 2.2.6 versions of Magento.

The problem with that is that the visibility of `getFilteredArray` is **not yet** changed in 2.2.5, so redeclaring it as private when it's protected there causes a PHP fatal error.
Could you alter your PR so the *local* `getFilteredArray` is named differently (even if it's a blatant copy) to avoid this issue ?

Regards,

**Comment by delyriand** [comment]
Hello @rbayet,

it's done ;)

**Comment by romainruaud** [comment]
so this one is correct now ? @rbayet can you check it against 2.2.5 and 2.2.6 ?

**Comment by rbayet** [comment]
2.2.5 (EE production mode) in catalog navigation + search : OK
2.2.6 (developer mode) catalog navigation OK, search KO

**Comment by delyriand** [comment]
@rbayet,

I confirm i have same problem with magento 2.2.7 in developer mode. It seems that issue is at the level of [Magento](https://github.com/magento/magento2/issues/17825).
Indeed, in search, we do not get block interceptor (ListProduct\Interceptor) so plugins are not called

**Pull request merged**
