### PR TITLE
Feature conditional optimizer backend

### PR DESCRIPTION
**Pull request by romainruaud**
- Creating new tables to store optimizer and categories/queries associations.
- Save/Read handler to save/load these links.
- Refactoring of Optimizer Ui component to separate the different modifiers (Preview part, conditional optimizer part).

### CODE REVIEW

**Comment by romainruaud** [comment]
As discussed together, here is the updated PR.

**Comment by afoucret** [comment]
Not sure if you have finished reworking it.
Still see separate tables, write handler and read handler for categories and search terms.

**Comment by romainruaud** [comment]
As discussed I will also rework the DataProvider to base it on Collection usage : this will imply to ensure optimizer collection is properly loading optimizer limitations.

**Comment by romainruaud** [comment]
I refactored the points we discussed this morning (merge the two tables in one, use collection in the dataprovider).

I also squashed my commits.

Regards

**Comment by afoucret** [comment]
Some minor concerns will be addressed when we will have the final review for the conditionnal optimizers feature branch.

Let you work on applying the optimizer

**Comment by romainruaud** [comment]
I already have it on a branch but will probably need to rebase it before contributing. I'll check this and submit PR as soon as I can.

**Pull request merged**
