### PR TITLE
Fixes #1248 Dropdown attributes values not saved

### LINKED ISSUE #1248: Dropdown attributes not saved in admin in 2.2.7
Ref: #1169 

When adding values to attributes of either dropdown, or multi-select type in Magento admin, the values are not saved.

### Preconditions

This was fixed for core 2.2.6, as mentioned in the release notes, and I've confirmed that the fix was successful, but after upgrade the Magento core to 2.2.7, the problem persists.

Magento Version : 2.2.7

ElasticSuite Version :  2.6.4

Environment : Production

Third party modules : None

### Steps to reproduce

1. Install Magento 2.2.7
2. Install Elasticsuite 2.6.4
3. From the admin, navigate to manage attributes, and attempt adding a new value to a attribute that's of either a dropdown type or a mult-select type
4. Save the attribute

### Expected result

1. Page is reloaded, displaying the new value

### Actual result

1. Page is reloaded, but new value has not been saved

### PR DESCRIPTION
**Pull request by rbayet**
Backported changes in native JS code (catalog and swatches handling).
Removed the indentation of catalog/product/attribute/js.phtml for easier comparison.

### CODE REVIEW

**Comment by rbayet** [comment]
Fixed on a CE 2.2.7

TODO : 
- test on EE 2.2.7
- test on CE/EE 2.2.6 (I'm not so sure that native changes are BC)

**Comment by rbayet** [comment]
The issue with the swatches at 2.2.5 and all versions before is that handling of POST variable `serialized_options` was only added in 2.2.6.
For regular attributes, the JS code is located in non-overriden JS file `vendor/magento/module-catalog/view/adminhtml/web/js/options.js`.

For the swatches, it's handled by `vendor/magento/module-swatches/view/adminhtml/web/js/product-attributes.js` and `vendor/magento/module-swatches/Controller/Adminhtml/Product/Attribute/Plugin/Save.php` which use a `serialized_swatch_values` POST variable 
```
        if (isset($data['frontend_input'])) {
            //Data is serialized to overcome issues caused by max_input_vars value if it's modification is unavailable.
            //See subject controller code and comments for more info.
            if (isset($data['serialized_swatch_values'])
                && in_array($data['frontend_input'], ['swatch_visual', 'swatch_text'])
            ) {
                $data['serialized_options'] = $data['serialized_swatch_values'];
                unset($data['serialized_swatch_values']);
            }
```

The issue is that the swatches JS file is overriden for our module purpose and the fix introduced there for #1248 
- should not work in 2.2.6 but seems to (??)
- will serialize options for a PHP counter-part that is not ready for it ...

**Comment by rbayet** [comment]
Considering that :
- the support for 'serialized_options' was added in 2.2.6 and is still there in 2.2.7
- with the support for 'serialized_swatch_values' was added in 2.2.6 and removed in 2.2.7
- the overridden `vendor/magento/module-swatches/view/adminhtml/web/js/product-attributes.js` is based on the 2.2.7 version 

there are now two new plugins `src/module-elasticsuite-swatches/Plugin/Catalog/Controller/Adminhtml/Product/Attribute/SavePlugin.php` and `src/module-elasticsuite-swatches/Plugin/Catalog/Controller/Adminhtml/Product/Attribute/ValidatePlugin.php` which deserializes the attribute options for versions prior to 2.2.6.

Successfull tests (with the swatches modules enable) for both EE and CE versions 
- 2.2.1
- 2.2.5
- 2.2.6
- 2.2.7

**Comment by romainruaud** [comment]
This fix is not that ugly after all... I was fearful that more crappy code would be needed to deal with all versions.

Seems good to me, let's hope Magento does not change it again for 2.2.8 and other minors ...

**Pull request merged**
