### PR TITLE
Fixes #987

### LINKED ISSUE #987: magento 2.2.5 + latest es stops compilation
You are probably aware of this already but 2.2.5 breaks es.

### Preconditions

Magento Version : 2.2.5 CE

ElasticSuite Version : 2.5.12

Environment : Production

### Steps to reproduce

1. Install magento 2.2.5 and elastic suite 
2. Compile

### Expected result

1. Compiles

### Actual result

1.
```
Declaration of Smile\ElasticsuiteCore\Model\ResourceModel\Search\Request\RelevanceConfig::saveConfig($path, $value, $scope, $scopeCode = 'default') 
must be compatible with Magento\Framework\App\Config\ConfigResource\ConfigInterface::saveConfig($path, $value, $scope = Magento\Framework\App\Config\ScopeConfigInterface::SCOPE_TYPE_DEFAULT, $scopeId = 0) 
in /home/jenkins/workspace/MagentoStaging/magento2/shop/vendor/smile/elasticsuite/src/module-elasticsuite-core/Model/ResourceModel/Search/Request/RelevanceConfig.php on line 99
```

Gotta love breaking changes in minor versions!

### PR DESCRIPTION
**Pull request by nntoan**

### CODE REVIEW

**Comment by afoucret** [comment]
@nntoan : Is it possible for you to rebase your query from branch 2.5.x.
We would like to provide this fix in the next maintenance release (2.5.13).

@romainruaud : Let you test the proposed solution against both Magento 2.2.5 and 2.2.4 and report the result.

**Comment by nntoan** [comment]
@afoucret Done, you now can rebase the branch in this PR.

**Comment by afoucret** [comment]
Still see all the commit from the master branch.

**Comment by nntoan** [comment]
@afoucret It can't change the fork across branch, no worries, I will close this PR and create a new one.

**Pull request closed without merging**
