### PR TITLE
Made the searchbar instantiatable multiple times

### PR DESCRIPTION
**Pull request by cartok**
Also rughly cleaned up the template 😉

### CODE REVIEW

**Comment by Seppmann** [comment]
Hi,
I updated from ES 2.10.10 to ES 2.10.11 (this feature is included since ES 2.10.11). 

**Search Bar wont open on click in mobile/responsive view.**

Testet on vanilla M2.4.3-p2, including Sample Data and ElasticSuite 2.10.11 - on Luma theme

Please let me know when there's a fix

Thanks and best regards

Sebastian

**Comment by cartok** [comment]
My bad, sorry. The label is configured for an input element with the id `search` but I removed the id from the input field. So I suggest to also generate a id for the input field:
```
$inputId = 'minisearch-input-' . $blockId;
```

**Comment by cartok** [comment]
Created issue and PR:
* https://github.com/Smile-SA/elasticsuite/issues/2668
* https://github.com/Smile-SA/elasticsuite/pull/2669

**Comment by Seppmann** [comment]
> Created issue and PR:
> 
>     * [Mobile search bar is not opening on click #2668](https://github.com/Smile-SA/elasticsuite/issues/2668)
> 
>     * [Fix #2668 #2669](https://github.com/Smile-SA/elasticsuite/pull/2669)
> 
> 
> Can someone test it?

Hi,
thanks!  I tested and its working :)

**Pull request merged**
