### PR TITLE
TableMaintainer 2.2.4 backward compat.

### PR DESCRIPTION
**Pull request by afoucret**

### CODE REVIEW

**Comment by afoucret** [comment]
Hi @djenvert nicobatty,

Could you please confirm this PR restore the 2.2.4 backward compat.

Thx for reporting

**Comment by ccasciotti** [comment]
Hi @afoucret,
I have the same issue, I've implemented this PR in my enviroment and I can confirm that it works with:

Magento Commerce 2.2.4
Smile ElasticSuite 2.5.13

I hope this help.

**Comment by pczerkas** [comment]
Hello,
unfortunaltelly, on 2.2.4
$this->objectManager->get('Magento\Catalog\Model\Indexer\Category\Product\TableMaintainer') 
throws ReflectionException
Class Magento\Catalog\Model\Indexer\Category\Product\TableMaintainer does not exist 
on indexer:reindex

**Comment by moejoee91** [comment]
Still not fixed in 2.2.4 unfortunately

**Comment by ccasciotti** [comment]
Sorry for my previous comment, it was a false positive, isn't fixed on 2.2.4. 
I think that it can be fixed by wrapping objectManager with a try-catch block.

**Comment by romainruaud** [comment]
Closed in favor of #1005

**Pull request closed without merging**
