### PR TITLE
Remove invalid characters

### PR DESCRIPTION
**Pull request by thomas-kl1**
Invalid comment tags prevent load of js scripts in adminhtml.

### CODE REVIEW

**Comment by thomas-kl1** [comment]
@romainruaud Hello could process it quickly? It's breaking the adminhtml area.

**Comment by romainruaud** [comment]
do you have a particular configuration for JS files ? We're not having the issue locally.

**Comment by thomas-kl1** [comment]
When I deploy statics with minification I have those characters in the generated requires config file and it throws a runtime error

**Comment by rbayet** [comment]
Replaced by #3222 on 2.10.x

**Comment by rbayet** [comment]
Nice catch @thomas-kl1 
I've rebased your commits on 2.10.x and squashed them in a new PR #3222

**Pull request closed without merging**
