### PR TITLE
Adding a "reference" field definition : ability to search by SKU.

### PR DESCRIPTION
**Pull request by romainruaud**
This a proposal of implementation according to discussion in #100 

Tested working against Luma default SKU values (MH06, MS09 etc...) and also with EAN13 values (3459379414678).

Let me know about it.

### CODE REVIEW

**Comment by romainruaud** [comment]
This PR brokes the Travis build because the "Field" class has now a complexity of 51... was 50 before. 
Seems hard to optimize, let me know if we can ignore or not if we decide to merge this one.

**Comment by southerncomputer** [comment]
Have you thought about pushing this patch into 2.3.x? it would help with complex sku field accuracy!

**Comment by afoucret** [comment]
@southerncomputer : 
I am not huge fan of this patch and work on a better solution that should be more generic and address the general problem of using custom analyzer on specific fields.
I fear, you will have to wait 2.4.0 for this patch. At the same time I don't think merging temporary solution is a good idea, since it can have side effect on ascendant compatibility ...

**Comment by maximehuran** [comment]
I need this functionality very quickly, if I switch to the 2.4 branch, will I can search products by SKU ?

**Comment by afoucret** [comment]
This PR will not be merged since a better implementation have been proposed (PR #300)

**Pull request closed without merging**
