### PR TITLE
Force scheduled reindexing of affected products

### PR DESCRIPTION
**Pull request by rbayet**
after a reset of positions and blacklist

### CODE REVIEW

**Comment by romainruaud** [comment]
Looks clean to me (code point of view), I let you merge and cascade it if it's working.

**Comment by rbayet** [comment]
> Looks clean to me (code point of view), I let you merge and cascade it if it's working.

Unfortunately, it covers the case where resetting everything after switching "Use default positions" from "Yes" to "No", but not the case immediately after that : falling back to "Use default positions" from "No" to "Yes" with positions and blacklist defined at the default level.
It seems the `dataHasChangedFor` does not work in this case (because of the default value of the `use_store_positions` at store_id 0 ?).

I'm trying to find a solution other than brute force which would consist in to unconditionnally write the affected product ids to the CL table if the indexer is in scheduled config.

**Comment by rbayet** [comment]
> I'm trying to find a solution other than brute force which would consist in unconditionnally write the affected product ids to the CL table if the indexer is in scheduled config.

Went half-way, condition went from 
``` 
        if (!empty($category->getAffectedProductIds()) 
            && $category->dataHasChangedFor('use_store_positions')
        )
```
to
```
        if (!empty($category->getAffectedProductIds())
            && ($category->dataHasChangedFor('use_store_positions') || (false == $category->getUseStorePositions()))
        )
```

**Comment by romainruaud** [comment]
Ok for me, as long it remains on a single responsibility plugin, I'm fine with it.

You can merge and cascade this one

**Pull request merged**
