### PR TITLE
Use display:flex for product list

### PR DESCRIPTION
**Pull request by fredden**
The product list in the admin is currently displayed as a 'grid' by floating all the elements left. This works when all items are of uniform height. When items aren't all uniform height, we get an inefficient use of space with big gaps to the left where items that are slightly higher mid-way along a 'row' blocks a large amount of space to its left. The next 'row' doesn't neatly line up with the bottom of the previous.

This pull request changes this to use `display: flex` for a better user experience.

### CODE REVIEW

**Comment by romainruaud** [comment]
Hi @fredden 

it's broken on my env, the button "clear product positions" is going to a wrong place : 

image

Regards

**Comment by fredden** [comment]
Thanks for flagging. I'll have a look to see what can be done about that.

**Comment by fredden** [comment]
@romainruaud please can you test again. I've adjusted the styles so that floating the button no longer interferes with the grid width.

**Comment by fredden** [comment]
Hi @rbayet. What can I do to help get this merged in?

**Comment by romainruaud** [comment]
Merged in 2.10.x, thank you for contributing

**Comment by fredden** [comment]
@romainruaud I can't see these changes here: https://github.com/fredden/smile-elasticsuite/blob/bb999d4460ea7c7200111e9c5859793bc3177254/src/module-elasticsuite-catalog/view/adminhtml/web/css/source/_module.less

With what commit were these changes added into `2.10.x`?

**Comment by romainruaud** [comment]
https://github.com/Smile-SA/elasticsuite/commit/741314d5c8ca568a963f147183f3f883a9f1974a

I just removed "justify-content: space-between;" cause it was buggy for me, and added some more nice-to-have css rules

**Comment by fredden** [comment]
Thanks for sharing that. I can see these commits now. It seems that I was looking at the `2.10.x` branch of my fork not the `2.10.x` branch of this repository. Sorry for the noise / confusion.

**Pull request closed without merging**
