### PR TITLE
Fixes #1321 Prevent js errors if tracker blocked (2.6.x)

### LINKED ISSUE #1321: JS errors and non working search with enabled ublock origin
Hi,

i use chrome with enabled ublock origin as adblocker with this configuration:
ublock

In this case is get js errors, because the js file `...Smile_ElasticsuiteTracker/js/tracking.js` is blocked:
jserrors

The bigger problem is, also the search function is not working in case of the js errors.

Fix:
Add a try catch to all `smileTracker` calls.

### PR DESCRIPTION
**Pull request by rbayet**
by browser plugin (ex: ublock origin)

### CODE REVIEW

**Comment by southerncomputer** [comment]
You might want to rename tracking.js - i did to fracking.js to avoid the ublock in the first place!

**Comment by rbayet** [comment]
Hi @southerncomputer,

Yes, I figured out it was the name of the JS file that was the source of the problem, but I'll let @romainruaud decide.

Regards,

**Comment by romainruaud** [comment]
Yes, we'll probably have to rename the tracker file.

But actually the try/catch is a proper workaround, and it should be here in any cases (we cannot break all pages due to tracking, whatever causes it to crash).

**Comment by romainruaud** [comment]
Fix #1321

**Pull request merged**
