### PR TITLE
Update AttributeAggregation.php

### PR DESCRIPTION
**Pull request by wouter-toppershops**
For `type` instead of `0` in the array

### CODE REVIEW

**Comment by wouter-toppershops** [comment]
See: https://github.com/Smile-SA/elasticsuite/issues/1234

**Comment by rbayet** [comment]
Hi @wouter-toppershops,

Can you change the merge branch to 2.7.X ?

Regards,

**Comment by rbayet** [comment]
Hello @wouter-toppershops,

Sorry again, I haven't been more explicit when I asked you to change the target merge branch and I probably missed that your source branch was your repository master too...

Could you pick your commit https://github.com/Smile-SA/elasticsuite/pull/1235/commits/2a8e18fae1f493ccbebf44a4ee904ae0bfa0d5c9 and add it to a clean feature/fix branch (re)based on 2.7.x ? 
I cannot merge the PR as it stands, it would merge 3 commits into 2.7.x.

PS: After that, you'd be probable safe to `--reset hard 6b386ba7ded3cdb0b1484ff620d7ecc6c0271ec0` _your_ master branch.

Regards,
Richard.

**Comment by wouter-toppershops** [comment]
@rbayet See Pull https://github.com/Smile-SA/elasticsuite/pull/1237

**Comment by rbayet** [comment]
@wouter-toppershops thanks !

**Pull request closed without merging**
