### PR TITLE
Store level merchandiser feature

### PR DESCRIPTION
**Pull request by rbayet**
TODO : 
- decide if we want to finalize and merge #1183 first (they will conflict ...) ?
- initialize store-level positions and blacklist as a copy of global/default positions and blacklist on first override (instead of resetting everything) + reset button ?
- at least french i18n
- extra tests (on CE and single store instances)

### CODE REVIEW

**Comment by rbayet** [comment]
TODO : 
- ~~decide if we want to finalize and merge #1183 first (they will conflict ...) ?~~
- ~~initialize store-level positions and blacklist as a copy of global/default positions and blacklist on first override (instead of resetting everything) + reset button ?~~
- ~~at least french i18n~~
- extra tests (on CE and single store instances)

**Comment by rbayet** [comment]
TODO : 
- ~~decide if we want to finalize and merge #1183 first (they will conflict ...) ?~~
- ~~initialize store-level positions and blacklist as a copy of global/default positions and blacklist on first override (instead of resetting everything) + reset button ?~~
- ~~at least french i18n~~
- extra tests (on CE and single store instances)
- - minor fix where the default/All Store Views positions and blacklist are not correctly previewed when a category is edited in a specific store view context (toggle on and off the preview/editing mode corrects the preview)

**Comment by rbayet** [comment]
TODO : 
- ~~decide if we want to finalize and merge #1183 first (they will conflict ...) ?~~
- ~~initialize store-level positions and blacklist as a copy of global/default positions and blacklist on first override (instead of resetting everything) + reset button ?~~
- ~~at least french i18n~~
- ~extra tests (on CE and single store instances)~
- - ~~minor fix where the default/All Store Views positions and blacklist are not correctly previewed when a category is edited in a specific store view context (toggle on and off the preview/editing mode corrects the preview)~~
- ~slight UI changes~

**Comment by romainruaud** [comment]
OK for me on my Magento 2.2

**Comment by romainruaud** [comment]
I let you merge and cascade this one

**Pull request merged**
