### PR TITLE
First implementation of the Stock Filter.

### PR DESCRIPTION
**Pull request by romainruaud**
Proposal of implementation for #124

### CODE REVIEW

**Comment by afoucret** [comment]
Hi @romainruaud,

I will not merged this one not because of code being badly written but because we plan to build a plugin to ElasticSuite with advanced inventory management and we do not want this feature to be duplicated into the core of ElasticSuite.

Stay tune for this feature.

**Comment by southerncomputer** [comment]
Any thoughts on implementing this with 2.8 ? It doesn't appear to add the filter by observer any more!

**Comment by AndriynomeD** [comment]
Any thoughts on implementing this with 2.9/2.10 ? In Elastic exists all needed data (stock.is_in_stock) but how to replace 'addFacetToCollection' function or how fix 'quantity_and_stock_status' attribute to deal with stock.is_in_stock?

**Comment by webcreative24** [comment]
@southerncomputer did you find out how to display a custom filter?

**Pull request closed without merging**
