### PR TITLE
Magento 2.4.5 (#2663): Fixing call to a member function getEuCountryList() on null

### PR DESCRIPTION
**Pull request by vahonc**

### CODE REVIEW

**Comment by romainruaud** [comment]
Hi Vadym, is this still backward-compatible with lower Magento versions ? 2.4.3/2.4.4 at least, I don't know if "Magento\Config\ViewModel\CountryFilter" exist in core Magento when using those versions.

**Comment by vahonc** [comment]
Yes, it looks like "Magento\Config\ViewModel\CountryFilter" doesn't exist in the previous version of Magento and it was released in M2.4.5. But I tried adding my fixes to M2.4.3 and didn't notice any issues, at least visible on the page, Search Relevance displaying as expected.

**Comment by walterbak** [comment]
In vendor/smile/elasticsuite/src/module-elasticsuite-core/view/adminhtml/layout/smile_elasticsuite_search_request_relevanceconfig_edit.xml, the block (without name and alias!) that instantiate Magento_Config::system/config/js.phtml 

`<block class="Magento\Backend\Block\Template" template="Magento_Config::system/config/js.phtml"/>`

must declare as argument 

```
<arguments>
        <argument name="countryFilter" xsi:type="object">Magento\Config\ViewModel\CountryFilter</argument>
</arguments>
```

If block had a name (or just an alias) it may be extended from an external module... but an anonymous block as it, cannot be extended out of the module.

**Comment by walterbak** [comment]
If you just add a name to the block
```
<block class="Magento\Backend\Block\Template" template="Magento_Config::system/config/js.phtml"/>
```
, we can hook it and add arguments from a custom module.

**Comment by romainruaud** [comment]
If I report this fix on a Magento 2.4.4 instance, I have a fatal error on Search Relevance page : 

```
Exception #0 (ReflectionException): Class "Magento\Config\ViewModel\CountryFilter" does not exist
```

I'll try to check how to handle this more cleanly.

**Comment by romainruaud** [comment]
Replaced by #2702

**Pull request closed without merging**
