### PR TITLE
Fixes #1213 Fulltext collection for category RSS

### LINKED ISSUE #1213: Fatal Error on RSS feed for category
When I go to rss for category I got fatal error intead of xml feed.

### Preconditions
Magento Version : 2.2.6, reproduced also on 2.2.2
ElasticSuite Version : 2.6.2, reproduced also on 2.5.14
Environment : Developer and Production

### Steps to reproduce
1. Enable RSS in Stores>Configuration:
```
rss/config/active => 1
rss/wishlist/active => 0
rss/catalog/new => 1
rss/catalog/special => 1
rss/catalog/discounts => 1
rss/catalog/category => 1
rss/order/status => 0
```
2. Disable "Display Out of Stock Products"
```
cataloginventory/options/show_out_of_stock => 0
``` 
3. Go to /rss and open one of the category, for example `rss/feed/index/type/category/cid/45/`

### Expected result
1. I want to see correct XML file.

### Actual result
1. I see fatal error from PHP
```
Fatal error: Uncaught Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in /var/www/creativeshop/brh/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 74
Error: Call to undefined method Magento\Catalog\Model\ResourceModel\Product\Collection\Interceptor::addIsInStockFilter() in /var/www/creativeshop/brh/vendor/smile/elasticsuite/src/module-elasticsuite-catalog/Plugin/LayerPlugin.php on line 74e
```

#### Important hint:
After change `cataloginventory/options/show_out_of_stock => 1` feeds is generated correctly.

### PR DESCRIPTION
**Pull request by rbayet**
feed dataprovider

### CODE REVIEW

**Comment by rbayet** [comment]
DONE : 
- fatal error fixed by injecting correct collection factory

TODO : 
- check that changing the collection type does not alter results

**Comment by romainruaud** [comment]
Is it ready to merge ? I see a todo.

**Comment by rbayet** [comment]
@romainruaud it's not ready to merge

**Comment by rbayet** [comment]
> DONE :
> 
>     * fatal error fixed by injecting correct collection factory
> 
> TODO :
> 
>     * check that changing the collection type does not alter results

The fix is not valid : while the fatal error is avoided, all category RSS feeds contain the same products, certainly because the (category) context is missing.

**Comment by romainruaud** [comment]
Since this one is a low priority, if it's not ready to be merged today, it will be discarded and postponed to next minor versions.

**Comment by rbayet** [comment]
@romainruaud Got it working.

**Pull request merged**
