### PR TITLE
Added dutch (and german) translations with Crowdin

### PR DESCRIPTION
**Pull request by lewisvoncken**

### CODE REVIEW

**Comment by rbayet** [comment]
Hello @lewisvoncken,

Is the PR supposed to be considered as complete ?

Regards,

**Comment by lewisvoncken** [comment]
> Hello @lewisvoncken,
> 
> 
> 
> Is the PR supposed to be considered as complete ?
> 
> 
> 
> Regards,

Hi,

Yes it is ready with Dutch translations!

**Comment by romainruaud** [comment]
That's so cool !

Many thanks Lewis !

But I can see there are also de_DE files with incomplete translations (filled with english ones). 

Any chance we can get them sorted or removed ? This could make people to consider we're having 100% of the module translated in german which is not the case actually.

Best regards

**Comment by lewisvoncken** [comment]
@romainruaud 
I have updated the German Translations as well.

**Comment by rbayet** [comment]
Hello @lewisvoncken,

I've just merged a PR onto 2.10.x and then 2.11.x with some [additional i18n strings](https://github.com/Smile-SA/elasticsuite/pull/3361/files#diff-5f22c2cbce3f765848dfe646df17015e03570a2e307f0a536332b7a67f03ba6f).
Please let me know if you intend to also add translation for those, otherwise, I'll probably pick this PR and create another one from it with all individual commits squashed.

Regards,

**Comment by rbayet** [comment]
Replaced by #3363 which contains all 36 commits rebased on top of 2.11.x and then squashed

Thanks @lewisvoncken !

**Pull request closed without merging**
