### PR TITLE
Fix category indexing in Magento 2.2.5

### PR DESCRIPTION
**Pull request by afoucret**

### CODE REVIEW

**Comment by mageho** [comment]
Thank you, it solved this issue in Magento 2.2.5

**Comment by nicobatty** [comment]
Hi, I don't know if this is volontary or not but this update is only compatible with M2.2.5 since the `Magento\Catalog\Model\Indexer\Category\Product\TableMaintainer` only exists in M2.2.5.

See here :

M2.2.4 : https://github.com/magento/magento2/tree/2.2.4/app/code/Magento/Catalog/Model/Indexer/Category/Product
M2.2.5 : https://github.com/magento/magento2/tree/2.2.5/app/code/Magento/Catalog/Model/Indexer/Category/Product

Maybe it should be considered a version 2.6.x and specified in the documentation.

**Comment by afoucret** [comment]
That is why I have used the ObjectManager.
But I have also used TrableMaintainer::class and it can't work.
My bad ...
I will fix it quickly.

**Comment by nicobatty** [comment]
Oh yes I did not look at the entire code, I just looked at the "use" statement. ;)

**Comment by afoucret** [comment]
Think we will try to release something Monday (Friday is not a good day for a release).

**Comment by afoucret** [comment]
PR #993 should fix the backward compat.
Propose you to continue the discussion there.

**Pull request merged**
