### PR TITLE
Remove test folder from autoload

### PR DESCRIPTION
**Pull request by rvitaliy**

### CODE REVIEW

**Comment by romainruaud** [comment]
Hi,

can you describe more what this PR is trying to achieve ?

**Comment by rvitaliy** [comment]
yes, of course!
I remove the tests classes from autoload to increase performance.
this classes usually can be excluded see
https://github.com/magento/magento2/blob/2.4-develop/composer.json#L345
https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps

**Comment by rbayet** [comment]
@romainruaud we don't have an `autoload-dev` section, is this a requirement if this PR is merged ?

**Comment by rbayet** [comment]
Hello @rvitaliy,

Why did you close this pull request ?

Regards,

**Pull request closed without merging**
