### PR TITLE
Fixes #2130 Convert Schema Scripts to DB Schema XML

### LINKED ISSUE #2130: Error during installation on Magento >=2.4.1
### Preconditions
I develop in a Docker environment including Elasticsearch 7.7.1, Redis 6, PHP 7.4 and MariaDB 10.4

Magento Version : 2.4.2 EE (tested in 2.4.0 EE, 2.4.1 CE and 2.4.1 EE, too)
ElasticSuite Version : 2.10.3
Environment : Developer

Third party modules :
- "cweagans/composer-patches": "^1.7"
- "magento/magento-coding-standard": "^6.0"
-  "phpunit/phpunit": "~9.2.0"

### Steps to reproduce
1. `composer require smile/elasticsuite`
2. `bin/magento module:enable Smile_ElasticsuiteCore Smile_ElasticsuiteCatalog Smile_ElasticsuiteSwatches Smile_ElasticsuiteCatalogRule Smile_ElasticsuiteVirtualCategory Smile_ElasticsuiteThesaurus Smile_ElasticsuiteCatalogOptimizer Smile_ElasticsuiteTracker Smile_ElasticsuiteAnalytics Smile_ElasticsuiteAdminNotification`
3. `bin/magento setup:config:set --es-hosts elasticsearch:9200`
4. `bin/magento setup:config:set --es-enable-ssl 0`
5. `bin/magento setup:upgrade`

### Expected result
1. No errors and a clean execution of the command `setup:upgrade`.

### Actual result
1. `Cache types config flushed successfully
Cache cleared successfully
File system cleanup:
/var/www/default/generated/code/Composer
/var/www/default/generated/code/Fastly
/var/www/default/generated/code/Magento
/var/www/default/generated/code/PayPal
/var/www/default/generated/code/Psr
/var/www/default/generated/code/Smile
/var/www/default/generated/code/Symfony
The directory '/var/www/default/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.smile_virtualcategory_catalog_category_product_position' doesn't exist, query was: CREATE TRIGGER trg_smile_virtualctgr_cat_ctgr_prd_position_after_insert AFTER INSERT ON smile_virtualcategory_catalog_category_product_position FOR EACH ROW
BEGIN
INSERT IGNORE INTO ``catalogsearch_fulltext_cl`` (``entity_id``) VALUES (NEW.``product_id``);
END`
2. If you run `setup: upgrade` again after this error, it will go through without errors. However, the trigger is then not created in the table.

### PR DESCRIPTION
**Pull request by pykettk**
## Description
Converts `InstallSchema` and `UpgradeSchema` scrips into `db_schema.xml` files and removes related functionality from accompanying helper classes.

#2130

### CODE REVIEW

**Comment by romainruaud** [comment]
Wow, congrats, that was a HUGE job to do this conversion process.

Is this finish ? In any case you can rebase to latest 2.10.x and force-push to ensure the integration tests will proceed.

Regards

**Comment by pykettk** [comment]
@romainruaud Thanks 🙂 I've rebased `2.10.x` and the integration tests are now passing. Please feel free to re-review 👍

**Comment by hostep** [comment]
Hi folks, what would be the status here?

Asking because I ran into https://github.com/Smile-SA/elasticsuite/issues/2130 for the 3rd or 4th time already when installing this module on a new shop and it would be nice if this could get fixed one day 🙂 

Thanks!

**Comment by romainruaud** [comment]
This will be part of the next master release (2.11.0).

I know it was quite old but we could not drop this as part of a minor release.

Regards and once again, many thanks for contributing this.

**Pull request merged**
