### PR TITLE
#2983 Add observer to load mandatory attributes on category collections

### PR DESCRIPTION
**Pull request by nige-one**
This will make sure that 'Virtual Categories' will correctly process product loading

### CODE REVIEW

**Comment by nige-one** [comment]
See https://github.com/Smile-SA/elasticsuite/issues/2983

**Comment by rbayet** [comment]
Hello @nige-one,

Could you refresh your PR by rebasing it on top of 2.11.x and force-pushing it ?

This way it would also trigger again the integration tests and we both could have a look at what failed on PHP 8.2 tests.

Regards

**Comment by nige-one** [comment]
Hi @rbayet here you go. Thanks for taking action

**Review by rbayet — APPROVED** [review]

**Comment by rbayet** [comment]
Replaced by #3044

**Pull request closed without merging**
