### PR TITLE
Update InventoryData.php to work with both return types

### PR DESCRIPTION
**Pull request by southerncomputer**
Update InventoryData.php to work with both return types: deprecated and inventorydatainterface...

### CODE REVIEW

**Comment by rbayet** [comment]
Self-note: if validated, squash and merge.

**Comment by rbayet** [comment]
@romainruaud Any philosophical requirement to also change the PHPdoc return type ?

**Comment by romainruaud** [comment]
I did not see anything non-working on this piece of code. Removing the return type should not break anything either.

But why do you want to remove it exactly @southerncomputer ? what's the use case ?

**Comment by southerncomputer** [comment]
We were having extremely long reindex times with the buggy MSI implementation in ee 2.3.3 - so we removed that library and only have cataloginventory which results in Deprecated::Class which is not compatible with inventoryinterface return type.. Throws an error with php 7.3.11 :(

**Comment by romainruaud** [comment]
Okay then it could be due to PHP 7.3 :)

We'll try to merge this one asap

**Pull request merged**
