### PR TITLE
Temp di fix for 2.3.2 magento upgrade with 2.8.0

### PR DESCRIPTION
**Pull request by southerncomputer**
This solved all of my front-end issues with 2.3.2 Magento Commerce Edition..

I did have to re-install the Plugin from 2.3.1 in catalog-inventory module that was missing or disable the Elasticsuite layer plugin for addisinstock method as well.

### CODE REVIEW

**Comment by arnoudhgz** [comment]
@southerncomputer what do you mean by `disable the Elasticsuite layer plugin for addisinstock` ?

**Comment by southerncomputer** [comment]
> 
> 
> @southerncomputer what do you mean by `disable the Elasticsuite layer plugin for addisinstock` ?

https://github.com/Smile-SA/elasticsuite/issues/1442

The AddIsInStock filter was removed from 2.3.2 - you have to disable it as in this thread ..

**Comment by southerncomputer** [comment]
https://github.com/Smile-SA/elasticsuite/pull/1444 is required to solve #1442 issue

**Comment by arnoudhgz** [comment]
Thanks @southerncomputer

**Comment by romainruaud** [comment]
replaced by #1461

**Pull request closed without merging**
