### PR TITLE
Use is_used_in_promo_rules instead of is_searchable for the image attribute.

### LINKED ISSUE #825: image attribute should not be set as searchable
We should set **is_used_in_promo_rules** to true instead.

### PR DESCRIPTION
**Pull request by afoucret**
Fix #825

### CODE REVIEW

**Comment by afoucret** [comment]
@romainruaud : can you test it please.

**Comment by romainruaud** [comment]
This one works as intended for me : 

- db schema properly updated
- 'image' field still in mapping and indexed

This can be merged.

Just one point, on my dev environment, 'image' was (this is legacy, I can't remember why) "used_in_spellcheck=1".

This implies that an attribute can be "is_searchable=0" BUT "is_used_in_spellcheck=1" and would then have "copy_to : 'spelling'" in the mapping.

Maybe this should be also fixed in a separate issue ?

**Comment by afoucret** [comment]
I fixed the is_used_in_spellcheck

**Comment by romainruaud** [comment]
Great for the "image" attribute, but I was thinking a more global fix, shouldn't we ?

Imho we should not be able to set an attribute to "is_searchable=0" and "is_used_in_spellcheck=1".

Your thoughts ?

**Comment by afoucret** [comment]
Yep. Propose a patch for this.

**Comment by romainruaud** [comment]
Acknowledged, I will work on a separate PR for this one.

You can merge this one for now.

**Pull request merged**
