### PR TITLE
Change !empty check to isset

### PR DESCRIPTION
**Pull request by peterjaap**
See https://github.com/magento/magento2/commit/7ab48b08dc6cda2853c95033e44152fa98f89258

### CODE REVIEW

**Comment by romainruaud** [comment]
Hi @peterjaap 

what's the point of changing this, exactly ? Does it change the behavior ?

The notable change in their PR is the fact that they now check whether they have a category_id filter or not. Previously they were checking only if there is a filter.

**Comment by peterjaap** [comment]
@romainruaud I don't know exactly why, but our upgrade testing tooling flagged this is a change in Magento which wasn't reflected in this preference in your extension

**Comment by romainruaud** [comment]
Ok @peterjaap 

this upgrade testing tool looks nice, is it public ? I'd like to have a peek on that, this might help us a lot as well, especially with Magento 2.4.7 coming.

regards

**Comment by peterjaap** [comment]
@romainruaud yes it is;
- https://github.com/ampersandHQ/ampersand-magento2-upgrade-patch-helper/ which output files you can feed to:
- https://github.com/elgentos/magento2-upgrade-gui

**Comment by rbayet** [comment]
Meh, @romainruaud, @peterjaap, I'm not so sure about this change.

In the pointed commit, they fix their sort of invalid test on the whether there is an applied category filter but IMHO they worsen the one on the search parameter.

I bet there are a ton of hastily coded custom frontend themes relying on the GraphQL API were people provide systematically the "search" parameter with an empty string value when there is no actual user search query instead of checking if the parameter should be provided in the first place.
That legacy `!empty` test prevented to enable the search mode if the query string was null or an empty string.
The new `isset` only protects against null values.

Regards,
Richard

**Pull request merged**
