### PR TITLE
Manage nice url for products displayed in virtual categories when the…

### PR DESCRIPTION
**Pull request by romainruaud**
… category path should be applied to URLs

Implements #66

### CODE REVIEW

**Comment by afoucret** [comment]
@romainruaud : Build have failed. Can you check please.

**Comment by romainruaud** [comment]
My bad.

I refactored this one and build is now OK.

Let me know

**Comment by afoucret** [comment]
Thx, I will review this one carefully before merging.

**Comment by romainruaud** [comment]
For me it's impossible to use the ```Product\Url``` model to retrieve the Url of product instead of using the ```getUrlKey()``` : 

- The product Url model will try to load from ```url_rewrite``` with the product/category couple and will fail
- The product Url model returns a "full Url" and not a raw "request path"

However, I have added a method to prevent the case where the product does not have any url_key (or when the attribute is not used in the listing) to fallback to the standard ```catalog/product/view/id``` pattern.

Regards

**Comment by afoucret** [comment]
Hi @romainruaud,

I have tested this development and there seems that there is an important test case you did not manage. The following example should be enough to understand it.

I have a virtual category (v1) inside another category and a product matching the rule.
So the product URL will be http://mysite/c1/v1/product.html.
But as every category is anchor in ElasticSuite, the product URL may be http://mysite/c1/product.html. This case seems to be missing especially if c1 is not a virtual category.

**Comment by afoucret** [comment]
Aditionnaly you will have to rebase the branch since there is a conflict with the #231 patch in the `frontend/di.xml` file

**Comment by afoucret** [comment]
This PR is outdated now.
Closed.

**Pull request closed without merging**
