### PR TITLE
Adding filterable attributes list by category.

### PR DESCRIPTION
**Pull request by romainruaud**
This is my proposal for #587 

It's actually working but I wanna have your opinion before going eventually further.

I have listed points that I could add to this PR before merging it if you are ok : 

- Staging is not managed. Maybe it is not worth it to allow to stage such settings ? Let me know.

- Actually the data is not inheritable. I think it could be a cool feature to be able to inherit from parent category : probably customers would only configure filterable attributes for top level categories and let the children inherit.

- This has not been plugged into Search results (when filtering on a category). We could do it but I'm not sure how we should manage attributes that are only filterable in search.

### CODE REVIEW

**Comment by afoucret** [comment]
Does look at the implementation detail but I see some usability optimizations :

* Design more consistent with color swatches (white header, more readable stripped display, more compact rows)

* Remove facet that will never be displayed because no products are matching. At least display a warning (No products : the facet will not be displayed)

**Comment by afoucret** [comment]
Display is better now.

You still have to rework : 

* the display of facet that are not currently available

* refactoring the Navigation block as I explained to you yesterday

**Comment by afoucret** [comment]
Problem when creating a new category : 
```
Fatal error: Method Magento\Ui\TemplateEngine\Xhtml\Result::__toString() must not throw an exception, caught Error: Call to a member function getFilterableAttributeList() on null in /Users/afoucret/local-apps/www/magento2-ee/vendor/magento/module-ui/Component/Wrapper/UiComponent.php on line 0
```

**Comment by romainruaud** [comment]
Ok @afoucret I think I'm nearly done.

One point remains : how should we deal with newly created categories ? With the "irrelevant attributes" filter, it's actually showing an empty table which is not really good. I'm thinking about simply removing the fieldset when creating a new category (as we do with virtual category rules).

Any opinion ?

**Comment by romainruaud** [comment]
I'm done @afoucret 

Ready for your final code review. 

Let me know !

**Comment by afoucret** [comment]
Please rebase and I will review it.

**Comment by romainruaud** [comment]
rebase done !

**Comment by afoucret** [comment]
Close since you have started refactoring of this PR

**Pull request closed without merging**
