### PR TITLE
Refactoring "special attributes" to allow extending them easily.

### PR DESCRIPTION
**Pull request by romainruaud**
Moving all hardcoded reference to "special attributes" (is_in_stock, price.is_discount, has_image) to a SpecialAttributeProvider extendable via the DI.

Here is also a proposal to implement a special attribute "is_new" injectable via DI : 

di.xml : 

```
    <type name="Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttributesProvider">
        <arguments>
            <argument name="attributes" xsi:type="array">
                <item name="is_product_new" xsi:type="object">Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute\IsNew</item>
            </argument>
        </arguments>
    </type>
```

"IsNew" class : 

```
<?php
/**
 * DISCLAIMER
 * Do not edit or add to this file if you wish to upgrade Smile Elastic Suite to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\ElasticsuiteCatalogRule
 * @author    Romain Ruaud <romain.ruaud@smile.fr>
 * @copyright 2017 Smile
 * @license   Open Software License ("OSL") v. 3.0
 */
namespace Smile\ElasticsuiteCatalogRule\Model\Rule\Condition\Product\SpecialAttribute;

use Smile\ElasticsuiteCatalogRule\Api\Rule\Condition\Product\SpecialAttributeInterface;
use Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory;
use Smile\ElasticsuiteCore\Search\Request\QueryInterface;

/**
 * "Is New" special attribute class
 *
 * @category Smile
 * @package  Smile\ElasticsuiteCatalogRule
 * @author   Romain Ruaud <romain.ruaud@smile.fr>
 */
class IsNew implements SpecialAttributeInterface
{
    /**
     * @var \Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory
     */
    private $queryFactory;

    /**
     * @var \Magento\Config\Model\Config\Source\Yesno
     */
    private $booleanSource;

    /**
     * Image constructor.
     *
     * @param \Smile\ElasticsuiteCore\Search\Request\Query\QueryFactory $queryFactory  Query Factory
     * @param \Magento\Config\Model\Config\Source\Yesno                 $booleanSource Boolean Source
     */
    public function __construct(QueryFactory $queryFactory, \Magento\Config\Model\Config\Source\Yesno $booleanSource)
    {
        $this->queryFactory  = $queryFactory;
        $this->booleanSource = $booleanSource;
    }

    /**
     * {@inheritdoc}
     */
    public function getAttributeCode()
    {
        return 'is_product_new';
    }

    /**
     * {@inheritdoc}
     */
    public function getSearchQuery()
    {
        $now = (new \DateTime())->format(\Magento\Framework\Stdlib\DateTime::DATETIME_PHP_FORMAT);

        $clauses = [];

        $newFromDateEarlier = $this->queryFactory->create(
            QueryInterface::TYPE_RANGE,
            ['field' => 'news_from_date', 'bounds' => ['lte' => $now]]
        );

        $newsToDateLater = $this->queryFactory->create(
            QueryInterface::TYPE_RANGE,
            ['field' => 'news_to_date', 'bounds' => ['gte' => $now]]
        );

        $missingNewsFromDate = $this->queryFactory->create(QueryInterface::TYPE_MISSING, ['field' => 'news_from_date']);
        $missingNewsToDate   = $this->queryFactory->create(QueryInterface::TYPE_MISSING, ['field' => 'news_to_date']);

        // Product is new if "news_from_date" is earlier than now and he has no "news_to_date".
        $clauses[] = $this->queryFactory->create(
            QueryInterface::TYPE_BOOL,
            ['must' => [$newFromDateEarlier, $missingNewsToDate]]
        );

        // Product is new if "news_to_date" is later than now and he has no "news_from_date".
        $clauses[] = $this->queryFactory->create(
            QueryInterface::TYPE_BOOL,
            ['must' => [$missingNewsFromDate, $newsToDateLater]]
        );

        // Product is new if now is between "news_from_date" and "news_to_date".
        $clauses[] = $this->queryFactory->create(
            QueryInterface::TYPE_BOOL,
            ['must' => [$newFromDateEarlier, $newsToDateLater]]
        );

        // Product is new if one of previously built queries match.
        return $this->queryFactory->create(QueryInterface::TYPE_BOOL, ['should' => $clauses]);
    }

    /**
     * {@inheritdoc}
     */
    public function getOperatorName()
    {
        return ' ';
    }

    /**
     * {@inheritdoc}
     */
    public function getInputType()
    {
        return 'select';
    }

    /**
     * {@inheritdoc}
     */
    public function getValueElementType()
    {
        return 'hidden';
    }

    /**
     * {@inheritdoc}
     */
    public function getValueName()
    {
        return ' ';
    }

    /**
     * {@inheritdoc}
     */
    public function getValue()
    {
        return 1;
    }

    /**
     * {@inheritdoc}
     */
    public function getValueOptions()
    {
        return $this->booleanSource->toOptionArray();
    }

    /**
     * {@inheritdoc}
     */
    public function getLabel()
    {
        return __('Only new products');
    }
}

```

### CODE REVIEW

**Comment by romainruaud** [comment]
This is a better version of the fix proposed in #582

**Comment by Koc** [comment]
@romainruaud  Is it possible do all calculations on indexation phase and filter by bool field? This could be performance optimization.

**Comment by romainruaud** [comment]
@Koc I'm not sure it would be worth it, doing it during indexation would slow down the indexing process, whereas doing it on query allow to benefit from Elasticsearch query cache. Also, the queries are not overly complicated and should not take long for the engine to compute.

@afoucret any opinion about this ?

**Comment by Koc** [comment]
For the most ecommerce projects reading from index doing more ofthen than reindexing IMHO.

**Comment by jsterling** [comment]
@romainruaud I'm using this code successfully in a custom module - however only the first clause (Product is new if "news_from_date" is earlier than now and he has no "news_to_date".) has any effect. 

Due to this, products which have a 'news_from_date' in the past are still visible. Can you help?

**Comment by gjportegies** [comment]
I've implemented this solution but I'm not getting any results on frontend and backend when creating a Virtual Category with the 'Only new products' rule. Is this solution should still relevant? I'm currently using ElasticSuite 2.8.0 on Magento 2.3.1

**Comment by jesse-thomas** [comment]
I had this working 6-9 months ago. After updating Magento and other modules in my development environment, I just noticed that I do not get new product results anymore. I get a no products found message.

**Comment by jesse-thomas** [comment]
@romainruaud can you update this to include the proper way to add a product attribute to the ES index? In this case we don't want the attribute to be searchable or sortable, just available for the virtual category query. Thanks!

**Comment by romainruaud** [comment]
@jesse-thomas just set your attribute to "is used for promo rules" and it will be indexed. It's a bit hacky actually but most of time it's enough on our projects.

regards

**Comment by JoostWan** [comment]
@romainruaud Thanks for this code. I'm busy to get this working for a client. But it's match the dates wrong. I get old products with a different new date in the category. 

When checked the data in Kibana a see the fields as a array instead of a string. I change for both attributes option _Use for Promo Rule Condition_ to **yes**. 

```
"news_from_date": [
      "2020-06-20 00:00:00",
      "2027-06-20 00:00:00"
    ],
    "news_to_date": [
      "2020-07-20 00:00:00",
      "2027-07-20 00:00:00"
    ],
```

Screenshot 2020-11-20 at 15 18 55
Screenshot 2020-11-20 at 15 18 25

**Comment by Mbertu** [comment]
@JoostWan I think that are all data from child products (one of your child products has the year setted to 2027)

**Comment by krunal2212** [comment]
How to add Date Range field for this Filter ? Is that possible ?

**Pull request merged**
